name: Lint and Test

on:
  push:
    branches: [main, feat/deployment]
  pull_request:
    branches: [main]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install backend dependencies and run linting
        working-directory: backend
        run: |
          pip install -r requirements-dev.txt
          # Run linting
          isort --check-only app/
          black --check app/
          flake8 app/ --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Run backend tests
        working-directory: backend
        run: |
          # Add your test command here when tests are available
          echo "Backend tests would run here"

  frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend dependencies and run linting
        working-directory: frontend
        run: |
          npm ci
          # Run linting
          npm run lint

      - name: Build frontend
        working-directory: frontend
        run: |
          npm run build

      - name: Run frontend tests
        working-directory: frontend
        run: |
          npm run test:ci
